/*



 */
export const DEVICE_CHANGED = 'DEVICE_CHANGED';
export const INIT_FIREBASE = 'INIT_FIREBASE';

export const DEVICE_HISTORY_RECEIVED = 'DEVICE_HISTORY_RECEIVED';
export const DEVICE_SETTINGS_CHANGED = 'DEVICE_SETTINGS_CHANGED';
export const DEVICE_READINGS_CHANGED = 'DEVICE_READINGS_CHANGED';
export const ALERT_CHANGED = 'ALERT_CHANGED';

export const DEVICE_SETTING_CHANGE = 'DEVICE_SETTING_CHANGE';
export const DEVICE_SETTING_RECEIVE = 'DEVICE_SETTING_RECEIVE';

export const USER_RECEIVE = 'USER_RECEIVE';

export const ALERT_NEW = 'ALERT_NEW';
export const ALERT_EDIT = 'ALERT_EDIT';
export const ALERT_SAVE = 'ALERT_SAVE';

export const ALERT_FIELD_CHANGE = 'ALERT_FIELD_CHANGE';
export const ALERT_RULE_SAVE = 'ALERT_RULE_SAVE';
export const ALERT_RULE_FIELD_CHANGE = 'ALERT_RULE_FIELD_CHANGE';

export const ALERT_DELETE = 'ALERT_DELETE';
export const ALERT_RECEIVE = 'ALERT_RECEIVE';



//change, delete, create, receive